### ISSUE TITLE
WebP not supported on Safari

### ISSUE THREAD

**Issue by bbrinx** [Egrodo/choochoo#1]
![screen shot 2019-01-06 at 12 45 07 am](https://user-images.githubusercontent.com/19491938/50732602-5dc6b100-114c-11e9-9a61-5d372d82550f.png)
The image format breaks on Safari. There should be a fallback for browsers that don't support WebP, as [recommended by Google](https://developers.google.com/speed/webp/faq)

**Comment by Egrodo** [comment]
Oof, that's a big oversight on my part. Really appreciate you pointing it out, I've fixed it here https://github.com/Egrodo/choochoo/commit/8628a6c26991f51261ae1c24190357240db86208 by adding picture tag and alternate sources. Thanks for pointing this out!
